### PR TITLE
Update the 'update_script' function in ct/hoarder.sh, other fixes

### PR DESCRIPTION
**Pull request by vhsdream**
This will allow Hoarder to be updated like most other apps. As far as I could tell, in this case an update will mean pretty much a full reinstall. Since the DB is located at /var/lib/hoarder and the env file at /etc/hoarder/hoarder.env, we don't need to worry about backing those up during the update.

I also updated the Github URLs for Hoarder in the update_script function because they were pointing to the old repo. The function also allows the SERVER_VERSION env var that is in the hoarder-web service file to be updated so the version is correctly displayed in the app itself.

### CODE REVIEW

**Review by MickLesk — APPROVED** [review]

**Comment by MickLesk** [comment]
image

The UI works, the workers to. But not the database, Is that also the case for you?

**Comment by vhsdream** [comment]
Oh it looks like the [database migration](https://github.com/vhsdream/prox-script-dev/commit/5e6721755469e79b642f06e89b93ddafb37a92f9#diff-c88d5e1e6bd3d6bbfcd539defd76e3e558dfb8f9a3feff82f88aef8251c03a17L222) got stripped from the install script!

**Comment by MickLesk** [comment]
In my script? Its available

**Comment by vhsdream** [comment]
Actually, looking over the install script it seems a lot of the changes made that were working have been reverted, and some of the redundant/unnecessary commands that the [developer was referring to](https://github.com/MickLesk/Proxmox_DEV/pull/2#issuecomment-2496133722) have been added back.

Also, I think the Meilisearch configuration is redundant too, aside from the key, as the locations of the dumps folder and data.ms folder will already default to `/var/lib/meilisearch`. The key in the Meilisearch config and the key in the Hoarder env file also need to match, otherwise Meilisearch will reject the search queries.

**Comment by MickLesk** [comment]
Have you an example? Ive removed the &&, and some echos. + added cli 
then i removed the VARIABLES (like DATA_DIR and co), because we dont support something like this, we use fixed paths. Ideally everything should be in /opt

I also didn't see the added value of using so many different paths. (Updates must be possible and uncomplicated).

What I have also removed is a new user / group. We deploy everything with the default user.

**Comment by vhsdream** [comment]
I agree I shouldn't have split the services into different users, although it is a best practice to limit privileges as far as I'm concerned (although this would be in an unprivileged LXC so perhaps pointless 😆 ). I knew that the scripts did not do that step since I have run tons of them myself, yet I still went ahead and put it in this one 🤦🏻‍♂️ 

For the DB migration, I'm referring to [lines 113 to 115](https://github.com/MickLesk/Proxmox_DEV/blob/e070f7cb55e5bd85b527fb658a9790d7cd845bbf/install/hoarder-install.sh#L113-L115). The dev mentioned that we don't need to run `pnpm dlx @vercel/ncc build migrate.ts -o /db_migrations` - that it was more of a Docker thing. I did find however that we still have to run `pnpm migrate` inside of `packages/db`. I think you may need to export the DATA_DIR variable before running that command, or you could just let it generate the DB and mv to the DATA_DIR after:

```bash
cd /opt/hoarder/packages/db
pnpm migrate
mv db.db /opt/hoarder_data
```
DATA_DIR being where it is works if that is convention, so long as it doesn't get deleted (or gets backed up somewhere) during the update. I need to remember to work within the confines of what exists, and that changes need to be discussed and reviewed and the pros and cons need to be weighed before implementing them. I'm still learning, but having fun too - it feels good to contribute just a little bit to carry on tteck's legacy.

PS I can't run the install scripts because I don't have the slant font for figlet - where do you get that?

**Pull request merged**
